/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as ChronexTokenContractJson } from "../chronex/ChronexToken.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace ChronexTokenTypes {
  export type Fields = {
    totalSupply: bigint;
    owner_: Address;
  };

  export type State = ContractState<Fields>;

  export type MintEvent = ContractEvent<{ to: Address; amount: bigint }>;
  export type BurnEvent = ContractEvent<{ from: Address; amount: bigint }>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  ChronexTokenInstance,
  ChronexTokenTypes.Fields
> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as ChronexTokenTypes.Fields;
  }

  eventIndex = { Mint: 0, Burn: 1 };
  consts = { PermissionsErrorCodes: { Forbidden: BigInt(0) } };

  at(address: string): ChronexTokenInstance {
    return new ChronexTokenInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<
        TestContractParams<ChronexTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getSymbol", params);
    },
    getName: async (
      params: Omit<
        TestContractParams<ChronexTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getName", params);
    },
    getDecimals: async (
      params: Omit<
        TestContractParams<ChronexTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: Omit<
        TestContractParams<ChronexTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getTotalSupply", params);
    },
    onlyOwner: async (
      params: TestContractParams<ChronexTokenTypes.Fields, { caller: Address }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "onlyOwner", params);
    },
    changeOwner: async (
      params: TestContractParams<
        ChronexTokenTypes.Fields,
        { newOwner: Address }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "changeOwner", params);
    },
    mint: async (
      params: TestContractParams<
        ChronexTokenTypes.Fields,
        { to: Address; amount: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "mint", params);
    },
    burn: async (
      params: TestContractParams<ChronexTokenTypes.Fields, { amount: bigint }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "burn", params);
    },
    upgrade: async (
      params: TestContractParams<
        ChronexTokenTypes.Fields,
        { newBytecode: HexString }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "upgrade", params);
    },
  };
}

// Use this object to test and deploy the contract
export const ChronexToken = new Factory(
  Contract.fromJson(
    ChronexTokenContractJson,
    "",
    "1536c243844586114e3c7f768f9b45bc0fef35c01f44e853db0fdcb3337d5cf5"
  )
);

// Use this class to interact with the blockchain
export class ChronexTokenInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<ChronexTokenTypes.State> {
    return fetchContractState(ChronexToken, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeMintEvent(
    options: EventSubscribeOptions<ChronexTokenTypes.MintEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      ChronexToken.contract,
      this,
      options,
      "Mint",
      fromCount
    );
  }

  subscribeBurnEvent(
    options: EventSubscribeOptions<ChronexTokenTypes.BurnEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      ChronexToken.contract,
      this,
      options,
      "Burn",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      ChronexTokenTypes.MintEvent | ChronexTokenTypes.BurnEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      ChronexToken.contract,
      this,
      options,
      fromCount
    );
  }

  methods = {
    getSymbol: async (
      params?: ChronexTokenTypes.CallMethodParams<"getSymbol">
    ): Promise<ChronexTokenTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        ChronexToken,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: ChronexTokenTypes.CallMethodParams<"getName">
    ): Promise<ChronexTokenTypes.CallMethodResult<"getName">> => {
      return callMethod(
        ChronexToken,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: ChronexTokenTypes.CallMethodParams<"getDecimals">
    ): Promise<ChronexTokenTypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        ChronexToken,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: ChronexTokenTypes.CallMethodParams<"getTotalSupply">
    ): Promise<ChronexTokenTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        ChronexToken,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends ChronexTokenTypes.MultiCallParams>(
    calls: Calls
  ): Promise<ChronexTokenTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      ChronexToken,
      this,
      calls,
      getContractByCodeHash
    )) as ChronexTokenTypes.MultiCallResults<Calls>;
  }
}
